### PR TITLE
Pin nightly version to a latest one known to be working

### PR DESCRIPTION
**Pull request by Xanewok**
Lightweight version of #131 - it'd be good to start with a good working base and incrementally work from there.

r? @Manishearth

### CODE REVIEW

**Comment by Xanewok** [comment]
It's worth noting that I used the same cargo bisect-rustc tool from #131 but with `test` script rather than `check` - there were some changes wrt `Eq` and `StructuralEq` that needed addressing in `nightly-2020-06-10` suggested there; atm this version (`nightly-2020-06-01`) is what builds and passes current tests.

**Comment by Manishearth** [comment]
Hmm, CI still fails, but r=me if you can get it to pass

**Comment by Xanewok** [comment]
That's because it tests using the newest nightly with `rustup-toolchain-install-master`: https://github.com/rust-dev-tools/rust-semverver/blob/0bbdabfc883a4e5c4d6dce21800b01649f0a70fa/ci/run.sh#L10-L21

If you don't mind, I'd prefer to change the CI script to just `cargo test` (that accounts for `rust-toolchain`) and then re-introduce the daily CI check using `rustup-toolchain-install-master` later at some point

**Comment by Xanewok** [comment]
CI is green now, merging as per above

**Pull request merged**
