### PR TITLE
Fix broken nightly build

### PR DESCRIPTION
**Pull request by gnzlbg**
The crate broke on nightly. This fixes that and bumps the version.

### CODE REVIEW

**Comment by gnzlbg** [comment]
@manisheart it appears that CI is still not enabled for rust-semverver. The travis build jobs are not starting on PRs. Also it would be nice to have daily cron jobs running here.

**Comment by ibabushkin** [comment]
Looks good to me. Keep in mind though that as of now we still use the more CI-friendly approach of first bumping the version and then pushing changes and publishing the crate. So the version bump is the beginning of a new release cycle so to speak. For simple PRs this is obviously not an issue, but I guess I should derive a contribution guide that incorporates some simple set of guidelines to handle this.

**Comment by gnzlbg** [comment]
> Keep in mind though that as of now we still use the more CI-friendly approach of first bumping the version and then pushing changes and publishing the crate. So the version bump is the beginning of a new release cycle so to speak. For simple PRs this is obviously not an issue, but I guess I should derive a contribution guide that incorporates some simple set of guidelines to handle this.

Ah sorry, I thought that the commit that was released was the one that should bump the version! I'll do it differently from now on.

**Comment by ibabushkin** [comment]
No big deal! Since I merge all the PRs anyway you can just not worry about version bumps at all, that should be even more low-friction :)

**Comment by ibabushkin** [comment]
I've published the new version on crates.io.

**Comment by gnzlbg** [comment]
Thank you, that should fix libc CI :)

**Pull request merged**
