### PR TITLE
Rustup to the latest nightly

### PR DESCRIPTION
**Pull request by JohnTitor**

### CODE REVIEW

**Comment by JohnTitor** [comment]
```
adding /home/travis/.cargo to cache
creating directory /home/travis/.cargo
adding /home/travis/build/rust-dev-tools/rust-semverver/target to cache
creating directory /home/travis/build/rust-dev-tools/rust-semverver/target
adding /home/travis/.rustup to cache
creating directory /home/travis/.rustup
adding /home/travis/.cache/sccache to cache
creating directory /home/travis/.cache/sccache

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

So, I think we've encountered the cache limit, added a tweak to reduce cache size.

**Comment by JohnTitor** [comment]
I think the installation failure could be ignored.
r? @Manishearth

**Comment by Manishearth** [comment]
Checks are still failing. I'd rather not merge stuff that breaks CI

**Comment by Manishearth** [comment]
File an issue about CI, please. Maybe we can switch to Actions which I've found to have a more reliable setup

**Comment by JohnTitor** [comment]
Sure thing, I'll file it in the morning tomorrow and maybe could setup as well.

**Comment by JohnTitor** [comment]
Filed it: #127

**Pull request merged**
