### PR TITLE
Rustup to latest nightly

### PR DESCRIPTION
**Pull request by JohnTitor**

### CODE REVIEW

**Comment by JohnTitor** [comment]
CI failure is unrelated.

**Comment by ibabushkin** [comment]
Hi! Sorry for my late reply, I a bit busy right now. If you don't mind I'll get the review and merge underway in roughly two weeks, the changes I glanced over look good so far. Thank you for contributing!

**Comment by JohnTitor** [comment]
@ibabushkin No worries! I use https://github.com/JohnTitor/rust-semverver/tree/fork-release branch in our project and it should work well (currently it's broken though :P). Feel free to cherry-pick commits and push them to this branch! (I allow edits from maintainers.)

**Comment by JohnTitor** [comment]
Or would you give me collaborator access? I'm available to work here to do some rustups if you want :)

**Comment by JohnTitor** [comment]
log test seems quite fragile so I'd skip updating at each time. Just let me know if we're ready to go, I'll update them.

**Comment by JohnTitor** [comment]
@ibabushkin: Friendly-ping, how about?

**Comment by ibabushkin** [comment]
Alright, I'm finally back in the game, reviewing now :)

Sorry to keep you waiting, chaos everywhere. Thank you for your patience.

**Comment by ibabushkin** [comment]
OK, the code changes look good!
I'll have a look at the log test, some weird things are happening there indeed. Maybe I can fix it, but if it proves to be non-trivial, it's not a blocker -- better to have a working master and no CI than neither (thanks me...)

**Comment by ibabushkin** [comment]
Do you mind if I squash your commits? Most of the commit messages don't contain much info, and I think the changes are readable enough as a single commit.

**Comment by ibabushkin** [comment]
Other than that, I'd gladly pull in your use of `anyhow`, that's a nicer way of dealing with our errors.

**Comment by JohnTitor** [comment]
> Do you mind if I squash your commits? Most of the commit messages don't contain much info, and I think the changes are readable enough as a single commit.

Sure thing, it aims to make review easy, squashed them.

> Other than that, I'd gladly pull in your use of anyhow, that's a nicer way of dealing with our errors. Same goes for the GH action stuff.

The use of `anyhow` requires to bump up `cargo` dependency so I'd like to submit another PR for that. GHA as well.

**Comment by ibabushkin** [comment]
You don't have to PR, I'll pull in your work myself and ask you for a quick review -- unless you insist of course!

**Comment by ibabushkin** [comment]
I'll make a release now.

**Comment by JohnTitor** [comment]
> You don't have to PR, I'll pull in your work myself and ask you for a quick review -- unless you insist of course!

Let's go ahead then :)

**Pull request merged**
