### PR TITLE
Fix compilation

### PR DESCRIPTION
**Pull request by gnzlbg**
Compilation is broken on nightly

### CODE REVIEW

**Comment by gnzlbg** [comment]
travis-ci is still disabled =/ @rust-dev-tools ping

**Comment by gnzlbg** [comment]
ping @ibabushkin

**Comment by ibabushkin** [comment]
LGTM, sorry for the latency.

**Comment by gnzlbg** [comment]
Don't worry, its that time of the year where people have exams. Good luck if you have any.

**Comment by gnzlbg** [comment]
@ibabushkin i'm trying to use this to verify that the `libc` crate does not introduce any backwards incompatible changes "by mistake" (we do some times do this, but it should be an explicit decision to do so, and not due to oversight). 

For this I need `rust-semverver` to essentially always compile properly with the latest nightly, and if things break, to be fixed ASAP. I don't know what would be the best way to achieve that. cc @rust-dev-tools

**Pull request merged**
