### PR TITLE
Port to the 2018 edition and cargo-semver cleanups

### PR DESCRIPTION
**Pull request by gnzlbg**
This commit ports rust-semverver to the 2018 edition and tidies cargo-semver a bit (more comments, some renames for clarity, etc.)

### CODE REVIEW

**Comment by gnzlbg** [comment]
I did the tidying of cargo-semver and rust 2018 in a different branch while trying to use `cargo metadata` instead of a cargo fork, but that did not pan out, so I moved them here.

The problem with `cargo metadata` is that it does not provide any information whatsoever about the paths of build artifacts, so we can't use it to try to find rlib files at all.

**Comment by gnzlbg** [comment]
The `features::regions` test has started breaking with the latest nightly release (the nightly before works fine).

**Comment by oli-obk** [comment]
Maybe we can modify the cargo metadata subcommand to emit the relevant info and extend the cargo metadata crate to expose those fields

**Comment by gnzlbg** [comment]
@oli-obk @ehuss suggested using the json output of `cargo build` for determining the paths of build artifacts like rlibs.

**Comment by ibabushkin** [comment]
I've looked at the `cargo build` feature that outputs JSON -- and it seems to be feasible to use for our purposes. I'll hack a version together that finds the rlibs using that and see whether this gives us a working version that doesn't rely on a patched cargo (which we cannot publish anyway).

**Comment by ibabushkin** [comment]
Hm, so far I haven't found a way to wire up the build plan output of `cargo build` (or rather, the mechanisms behind it) with our implementation in `cargo-semver`, but I believe that we can substitute some of the compilation logic with internals of cargo build if we are careful (using temporary directories if necessary).

**Comment by ibabushkin** [comment]
Alright, I managed to build a working (albeit currently quite ugly) solution. Cleanup I'll do later, but meanwhile we can merge this. Keep in mind I temporarily reverted some of the changes here (namely the dependency on the cargo fork) for now. Maybe we should discuss a clean solution to the whole cargo forking story. Thanks for your effort, your various issues and PRs certainly made this fix way easier!

**Pull request merged**
