### PR TITLE
Add flag --api-guidelines to silence non-technical breaking changes.

### LINKED ISSUE #58: Distinguish between hard breaking changes and soft breaking changes
Sometimes a crate wants to have slightly loser definition of breaking changes. i.e. changes are unlikely to break consumers. This can include things like adding a function to an impl.

@kvark

### PR DESCRIPTION
**Pull request by gnzlbg**
Closes #58 . 

This PR builds on #79 and adds a `--api-guidelines` flag that silences non-technical breaking changes. Let me know what you think about the general approach, there are a couple of ways to pursue this. We can also chat about this if you prefer.

### CODE REVIEW

**Comment by ibabushkin** [comment]
This looks good to me as well, and is roughly what I would imagine such a feature would be implemented like. What other possibilities do you have in mind that actually differ significantly in terms of flexibility and functionality? Otherwise, I'd merge this and update the README and so on to push out a new release. Thanks!

**Comment by gnzlbg** [comment]
So I don’t know if it might make sense to offer more control over the
different types of issues that produce warning / errors.

I imagine that for most people they want to either see errors + warnings,
or only errors, which is what this flag provides (IIUC warnings are
produced by “technical” breaking changes only anyways).

Arguably if one wants more control one can always provide a flag for that
in the future. What are your thoughts on this?

**Comment by ibabushkin** [comment]
Well, to the best of my knowledge such a feature would require a bit more complexity than is obvious, mostly because the categorization of changes into technically breaking and breaking is somewhat arbitrary and based on the assumption that some specific situations that are indeed breaking don't appear often enough in real projects to warrant a major version bump. The flexibility of being able to ignore such cases is certainly helpful, but in the long run we'd need a mechanism to control this on a per-project basis, allowing the user to provide a configuration of how these somewhat subtle changes ought to be treated, while defaulting to a resonable default.

Such a feature would be orthogonal to the given flag, so I believe merging it as-is would be a good first step, but once I get around to actually implementing that, we'd need documentation on every change type, and some updates to flag names etcetera. What do you think?

**Comment by gnzlbg** [comment]
I agree with you that it is an orthogonal feature. This flag (and its
absence) cover the 99.99% of the cases, and for finer grained control we
might want to offer a different more flexible approach like a toml
 configuration file.

**Comment by ibabushkin** [comment]
On 2018-12-08, gnzlbg wrote:
> I agree with you that it is an orthogonal feature. This flag (and its
> absence) cover the 99.99% of the cases, and for finer grained control we
> might want to offer a different more flexible approach like a toml
>  configuration file.

Alright then. I'll merge this as-is then and start implementing the
finer-grained configuration. Thank you for you contributions, it's
really appreciated given my current lack of time.

**Comment by gnzlbg** [comment]
As an update, my priority right now is enabling rust-semverver in libc CI.
The problem with libc is that we don’t really have any tests for APIs and
while doing refactoring it is too easy to remove APIs in some
configurations by mistake.

The only piece missing is cargo semver returning a non zero error code when
an error is encountered. I talked with oli
-obk (from miri and clippy) and they told me how to update the compiler
drivers to “the modern” way. That should automatically simplify things and
give us that so I will try to do that next.

**Pull request merged**
